module.exports = {
    station: require('./prod/station.js'),
    mpd: require('./prod/mpd.js'),
    mpc: require('./prod/mpc.js'),
    icecast: require('./prod/icecast.js'),
    channels: require('./prod/channels.js'),
    storage: require('./prod/storage.js'),
    server: require('./prod/server.js'),
    buttons: require('./prod/buttons.js'),
    shows: require('./prod/shows.js'),
    show: require('./prod/show.js'),
    playlist: require('./prod/playlist.js'),
    inputs: require('./prod/inputs.js'),
    input: require('./prod/input.js'),
    darkice: require('./prod/darkice.js'),
    ffmix: require('./prod/ffmix.js'),
};
