---
- name: CREATING THE PM2 HOME DIRECTORY
  file:
    path: "{{pm2_home}}"
    owner: "{{pm2_user}}"
    group: "{{pm2_user}}"
    mode: 0775
    state: directory
    recurse: yes
  become: yes

- name: ADDING PM2_HOME VARIABLE TO .bashrc
  lineinfile:
    dest: ~/.bashrc
    line: export PM2_HOME={{pm2_home}}

- name: CREATING PM2 STARTUP SCRIPT BY USING A SERVICE TEMPLATE
  template:
    src: service.j2
    dest: "/etc/systemd/system/{{pm2_service_name}}"
    mode: 0777
  become: yes

- name: UPDATING PM2
  command: "{{pm2_bin}} update"

- name: SERVICE DAEMON RELOAD
  command: systemctl daemon-reload
  become: yes

- name: RESTART PM2 SERVICE
  service:
    name: "{{pm2_service_name}}"
    state: restarted
  become: yes

- name: ADDING THE APP TO PM2
  shell:
    cmd: "{{pm2_bin}} start index.js -n station"
    chdir: "{{pm2_app_folder}}"